#!/bin/bash

VERSION="2.0"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RELEASES_DIR="$PROJECT_DIR/releases"

echo ""
echo "  ██████╗ ██████╗ ██████╗ ███████╗██╗  ██╗"
echo " ██╔════╝██╔═══██╗██╔══██╗██╔════╝╚██╗██╔╝"
echo " ██║     ██║   ██║██║  ██║█████╗   ╚███╔╝ "
echo " ██║     ██║   ██║██║  ██║██╔══╝   ██╔██╗ "
echo " ╚██████╗╚██████╔╝██████╔╝███████╗██╔╝ ██╗"
echo "  ╚═════╝ ╚═════╝ ╚═════╝ ╚══════╝╚═╝  ╚═╝"
echo ""
echo "     DRACULA - Build Script v$VERSION"
echo "======================================="

rm -rf "$RELEASES_DIR/chrome" "$RELEASES_DIR/firefox" "$RELEASES_DIR/firefox-v3"
mkdir -p "$RELEASES_DIR/chrome" "$RELEASES_DIR/firefox" "$RELEASES_DIR/firefox-v3"

echo ""
echo "[1/3] Gerando release para Chrome (Manifest v3)..."
cd "$PROJECT_DIR/chrome"
zip -rq "$RELEASES_DIR/chrome/codex-dracula-chrome-v$VERSION.zip" . -x "*.DS_Store" -x "__MACOSX/*"
echo "      -> releases/chrome/codex-dracula-chrome-v$VERSION.zip"

echo ""
echo "[2/3] Gerando release para Firefox (Manifest v2)..."
cd "$PROJECT_DIR/firefox"
zip -rq "$RELEASES_DIR/firefox/codex-dracula-firefox-v2-v$VERSION.zip" . -x "*.DS_Store" -x "__MACOSX/*"
cp "$RELEASES_DIR/firefox/codex-dracula-firefox-v2-v$VERSION.zip" "$RELEASES_DIR/firefox/codex-dracula-firefox-v2-v$VERSION.xpi"
echo "      -> releases/firefox/codex-dracula-firefox-v2-v$VERSION.zip"
echo "      -> releases/firefox/codex-dracula-firefox-v2-v$VERSION.xpi"

echo ""
echo "[3/3] Gerando release para Firefox (Manifest v3)..."
cd "$PROJECT_DIR/firefox-v3"
zip -rq "$RELEASES_DIR/firefox-v3/codex-dracula-firefox-v3-v$VERSION.zip" . -x "*.DS_Store" -x "__MACOSX/*"
cp "$RELEASES_DIR/firefox-v3/codex-dracula-firefox-v3-v$VERSION.zip" "$RELEASES_DIR/firefox-v3/codex-dracula-firefox-v3-v$VERSION.xpi"
echo "      -> releases/firefox-v3/codex-dracula-firefox-v3-v$VERSION.zip"
echo "      -> releases/firefox-v3/codex-dracula-firefox-v3-v$VERSION.xpi"

echo ""
echo "======================================="
echo "Build concluido."
echo ""
echo "Releases gerados:"
echo ""
echo "Chrome:"
ls -lh "$RELEASES_DIR/chrome/"
echo ""
echo "Firefox (Manifest v2):"
ls -lh "$RELEASES_DIR/firefox/"
echo ""
echo "Firefox (Manifest v3):"
ls -lh "$RELEASES_DIR/firefox-v3/"
